modLoader="javafml"
loaderVersion="[43,)"
license="All rights reserved"

[[mods]]
modId="asyu_rpg"
version="${file.jarVersion}"
displayName="Example Mod"
logoFile="asyu_rpg.png"
credits=""
authors="Asyunelus"

description='''
'''

[[dependencies.asyu_rpg]]
    modId="forge"
    mandatory=true
    versionRange="[43,)"
    ordering="NONE"
    side="BOTH"
    
[[dependencies.asyu_rpg]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.3,1.20)"
    ordering="NONE"
    side="BOTH"
